# Database - Lit Render en priorité, sinon utilise la valeur par défaut après le colons ':'
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://ep-bold-glade-atbar3zi-pooler.c-9.us-east-1.aws.neon.tech/neondb?sslmode=require}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:neondb_owner}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:npg_sxc0OESrb1kg}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# JWT
jwt.secret=${JWT_SECRET:okane_secret_key_2025_very_long_and_secure}
jwt.expiration=3600000
jwt.refresh-expiration=604800000

jwt.expiration-ms=3600000
jwt.expiration_ms=3600000
# Server
server.port=8080